name: Update Snake Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate Snake Game Image
      run: node generate-snake-image.js # Your script to generate the image

    - name: Commit and push updated image
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: your.email@example.com
        message: 'Update Snake game image'
